### ISSUE TITLE
Camera width/height should be numeric

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcubecore#1051]
In https://github.com/mxcube/mxcubeweb/pull/1462#discussion_r1808431660, I've noticed that `HWR.beamline.sample_view.camera.get_width/height()` returns strings instead of numbers. Can this be changed by any chance? This would avoid a conversion in the front-end.

**Comment by walesch-yan** [comment]
Did you use a specific camera device to test this? At least for the mockup camera `HWR.beamline.sample_view.camera.get_width/height()` always returns an int when I tried it out.

**Comment by axelboc** [comment]
No, just the default mock environment. This is what I get from the `/sampleview/camera` endpoint (defined in `samplecentring.py`):

![image](https://github.com/user-attachments/assets/43647dd6-1610-42b5-bfbd-17651ab6f36c)

You're right, though, it doesn't come from `get_width/height()` but from `HWR.beamline.sample_view.camera.get_stream_size()`, because the default config has `VIDEO_FORMAT: MPEG1` under `mxcube` in `server.yaml`: https://github.com/mxcube/mxcubeweb/blob/develop/mxcubeweb/core/components/beamline.py#L109-L112

**Comment by walesch-yan** [comment]
Yes, you are right `HWR.beamline.sample_view.camera.get_stream_size()` does return a string, and does so for every type of camera. And I agree that a function called `get_stream_size` should return a tuple of `int/float` rather than a list of `strings`. 

I think the reason behind it is that we set the stream_size as string since it needs to be for the usage of the video_streamer, but we could convert it in the `get_stream_size` (which is never called in `mxcubecore`).
