### ISSUE TITLE
Move files not describing hardware objects from HardwareObjects to Utils

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubecore#352]
Hi all,

As we are doing anyway lots of changes, I would like to suggest to move the following files to a new utils (Utils) directory:
```
GetStaticPars.py
NamedState.py
SimpleHTML.py
XSDataAutoprocv1_0.py
XSDataCommon.py
XSDataControlDozorv1_1.py
XSDataMXCuBEv1_3.py
XSDataMXv1.py
autoprocessing.py
edna_script.sh
queue_entry.py
queue_model_enumerables.py
queue_model_objects.py
sample_centring.py
```
Should it be utils or Utils or any other name?
Afterwards HardwareObjects directory would contain just hardware objects.

**Comment by rhfogh** [comment]
Hmmm, maybe.
You are quite right this is the time to clean up -  and cleaning would help. But I am not quite sure about the selection criterion.  For one thing, are AbstractCollect, EdnaWorkflow, GPhLWorkflow, or ShapeHIstory 'HardwareObjects', in that sense? For another, queue_entry and queue_model_objects are hardly 'Utils', they are the core of the queueing system. So, yes, but could we be a little clearer about what should live where?

**Comment by IvarsKarpics** [comment]
You are right @rhfogh . It is a discussion starter. For me ShapeHistory, Queue, BeamlineSetup are hardware objects, because they inherit hardware objects, but one could think about structure like:
+ HardwareObjects
+ Queue
  * QueueManager
  * QueueModel
  * queue_entry
  * queue_model_enumerables
  * queue_model_objects
+ Utils

**Comment by marcus-oscarsson** [comment]
I'm not so sure about this. I think we need to extend the concept of hardware objects or add a new concept that encapsulates more abstract entities, like queue, shapes and general procedures.

We have used HardwareObjects for this since we have not had something better, but I think its maybe time to find another solution.  The real advantage with the creating them as HardwareObjects have been that they are easy to configure through xml files. These objects are not taking advantage of the control system integration, commands and channels, so they don't need to be HardwareObjects.

We have said that we would like to redesign the queue, among other things. I think that we should first discuss what we would like the queue to be like before we start moving things around.

I would also be a bit careful of what we put in Utils so that it does not become a "dark corner"

Marcus

**Comment by IvarsKarpics** [comment]
A new directory core, components to store not the hardware objects?

**Comment by marcus-oscarsson** [comment]
Can I close this one or should we keep it open for later ?
