### ISSUE TITLE
Replace all CamelCase with snake_case

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/mxcubecore#527]
If we already doing so many changes, what about replacing all camel cases (getProperty, getValue, etc) with snake cases.
I can do this after all open PRs are merged.

- [x] BaseHardwareObjects
- [x] addChannel to add_channel
- [x] addCommand to add_channel
- [x] abstract
- [x] mockup

**Comment by beteva** [comment]
Good idea. I thought, though, that  @rhfogh was going to do this. Whoever does the job, thank you and courage!

**Comment by marcus-oscarsson** [comment]
Yes its a great idea !, also looking at the command and channels would be a good idea. Who ever does this, be careful when doing get/setValue, since its not only used by us but also by other libraries.

**Comment by rhfogh** [comment]
@IvarsKarpics 
Indeed, please do.

I had planned on stopping where I was, because 1) I have done a lot already, 2) I need to spend some time on other thinsg soon, 3) I was unsure if some of the camelCase function calls were linked to external functions in hardware, channels, or XMLRPC, so I could not modify them blindly.
But great if you can take it over.

**Comment by IvarsKarpics** [comment]
@marcus-oscarsson yes, of course. I would not do a blind replace. Ok, lets wait till all PRs are closed.

**Comment by marcus-oscarsson** [comment]
:), agree

**Comment by marcus-oscarsson** [comment]
PR #437 merged

**Comment by marcus-oscarsson** [comment]
TBD

**Comment by marcus-oscarsson** [comment]
Closing this as the main chunk of the work have been done ! Well done everyone you all deserve a big pat on the back and some Champagne ;)
