### ISSUE TITLE
mxcubecore/Command/Epics.py -- polling & callbacks bugs (?)

### ISSUE THREAD

**Issue by keara-soloway** [mxcube/mxcubecore#631]
1. In `EpicsCommand.__init__(...)`, [line 74](https://github.com/mxcube/mxcubecore/blob/master/mxcubecore/Command/Epics.py#L74) reads:
`self.valueChanged(self.pv.get(as_string=self.read_as_str, timeout=0.1))`
This produces an `AttributeError` in my setup, but things work when this line is changed to:
`self.value_changed(self.pv.get(as_string=self.read_as_str, timeout=0.1))`

2. In `EpicsCommand.value_changed(...)`, [line 139](https://github.com/mxcube/mxcubecore/blob/master/mxcubecore/Command/Epics.py#L139) reads:
`callback = self.__value_changed_callback_ref(value)`
This is causing an exception in all of the `Poller`'s callbacks to this function, unless the line is changed to:
`callback = self.__value_changed_callback_ref()`

2. There seems to be a python2/3 compatibility issue that is causing the weakref for the `EpicsCommand.__value_changed_callback_ref` on [line 170](https://github.com/mxcube/mxcubecore/blob/3c4e7ae5ae12111abb377078e3a82ba6bd02216f/mxcubecore/Command/Epics.py#L170) to be dead as soon as it is created. In [mxcubecore/saferef.py -- the function safe_ref](https://github.com/mxcube/mxcubecore/blob/3c4e7ae5ae12111abb377078e3a82ba6bd02216f/mxcubecore/saferef.py#L8) checks for two attributes of `target` that are not consistent with python3 (`im_self` and `im_func`). From [the docs from python2.7.18 Data model"](https://docs.python.org/2/reference/datamodel.html#the-standard-type-hierarchy): "Changed in version 2.6: For Python 3 forward-compatibility, `im_func` is also available as `__func__`, and `im_self` as `__self__`." I changed `im_self`  to `__self__` and `im_func` to `__func__` in my local copy of mxcubecore/saferef.py, and that worked to fix things in my setup.
_Another_ thing that worked to fix the problem, as suggested by Marcus (thanks!):
In the imports for mxcubecore/Command/Epics.py, change line 30:
`from mxcubecore import Poller, saferef`
into:
`from mxcubecore import Poller`
`from mxcubecore.dispatcher import saferef`

**Comment by laispc** [comment]
Hi @keara-soloway , thanks again for the identifying the issues and for the references.

I just tested theses fixes (and other details) with both mxcubeqt and mxcube3 and I am uploading a MR/branch here https://github.com/mxcube/mxcubecore/pull/632, please see if this branch work for you too. :)

1) `valueChanged` indeed has to be modified to `value_changed`. I think it was a typo introduced in the last merge on Epics.py. Sorry for this! I fixed that in the branch.

2) Both `callback = self.__value_changed_callback_ref(value)` and `callback = self.__value_changed_callback_ref()` is working for me. But I agree that it is better to remove the argument. Fixed in the branch.

3) This import is also not breaking for me for some reason. But I suggest that we make the import as suggested by Marcus (seems more pythonic to me), so I changed that in the branch. 

Also, I think that `im_self` and `im_func` should be fixed in saferef.py as you said **or** we could even remove this file, as dispatcher.py does the job and seems not to be used by any part anymore. What do you think, @keara-soloway and @marcus-oscarsson ? Thanks!
