### ISSUE TITLE
Update contributing guidelines?

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#662]
Actually reading the contributing guidelines I was surprised by the contents.

1) Reviewers are apparently *required* to test the PR before approving.
2) It is all organised around reviewers getting requested. They cannot be bypassed, so a missing review will hold everything up. Once the last reviewer has spoken, he should merge the PR, leaving no time for third parties to contribute. 

On 1) a lot of PRs cannot be tested, except at the right beamline. Many of my PRs cannot be tested unless you have global phasing installed. Also, running a test is a lot more demanding than looking at the code, particularly if you are supposed to exercise all the various code paths. I would be more than happy if the submitter of the PR had tested it, preferably both on his own beamline and in mock mode.

I submit that the way we currently work does not match the contributing guidelines. Being rather literal-minded, I would prefer if we adapted the guidelines to the way we work, or vice versa.

**Comment by beteva** [comment]
1. Agree with @rhfogh, not always possible for a reviewer to test the core. The contributor presumably has tested the code  before submitting a PR. I guess what was meant by testing by the reviewer was in case of non site-specific code the reviewer checks if its own environment is not broken by the PR. Maybe we should omit this part and only specify the compulsory tools we've chosen for a better code quality - black, pylint.
2. What @rhfogh is afraid of is true - it looks like we leave no time for a third party to react. On the other hand it has been decided like this, because some PRs were not merged for a long time. So now we do have this rule. I think we should keep it like this. There is always a possibility for a third party to speak (even after the PR has been merged). If need be, we could always make a new PR, with the changes, requested by the third party. We also have the rule of two approvals before merging the PR, so in reality it leaves some time for anybody, who is part of the project, to make comments.

**Comment by rhfogh** [comment]
Do we still have the rule of two approvals? I could not find it in the contributing guidelines.

Actually I thought things were working fairly well as it was, but I just want to be sure that the guidelines and the accepted practice actually match.

**Comment by marcus-oscarsson** [comment]
You are right that the contributing guidelines are not really reflecting the current way we are working and I agree that we should update them so that it does. We should perhaps even reconsider/rethink the current way we are working a little bit. I have some ideas that we could discuss on or next meeting. 

I suggest that we start our next meeting with a very short review of current topics to discuss and then dispatch them for discussion in appropriate forums, i.e for discussion here until the February meeting, then continue with the workshop.

What do you think ?

**Comment by rhfogh** [comment]
Makes perfect sense, @marcus-oscarsson

**Comment by rhfogh** [comment]
Too old now. If this is still relevant we can restart an issue
