### ISSUE TITLE
Queue / Workflow working group

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#675]
This is a place to make suggestions and comments, concerning the execution queue, incorporation of workflows, and abstract procedures. Open to all MXCuBE developers who have an interest in these topics..

**Comment by rhfogh** [comment]
X-ray centring

I would propose looking at X-ray centring as a first case. We seem to agree that a general way of calling X-ray centring would be good to have. Can we collect the existing implementations as use cases, to decide on parameters and interfaces? Which of the possible implementations would make sense?

**Comment by rhfogh** [comment]
Is this issue still live, or should we let it die?

**Comment by marcus-oscarsson** [comment]
Lets ask 007 :), jokes apart. I think we can put this on hold for the moment, some of it have been addressed, I believe, and discussions related to this will probably be reiterated after summer. However this issue is quite broad so we should probably close it and open more specific issues when we have something more clear ?

**Comment by rhfogh** [comment]
I do not think 007 would use an execution queue - he would just get on with the job ;-)
